# Generated by Django 4.2.6 on 2023-10-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="banned",
            field=models.BooleanField(default=False),
        ),
    ]
