# Generated by Django 4.2.6 on 2023-10-11 18:42

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_member_banned"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="profile_pic",
            field=models.ImageField(
                null=True, upload_to=account.models.Admin.upload_file_name
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="profile_pic",
            field=models.ImageField(
                null=True, upload_to=account.models.Member.upload_file_name
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="profile_pic",
            field=models.ImageField(
                null=True, upload_to=account.models.Staff.upload_file_name
            ),
        ),
    ]
