# Generated by Django 4.2.6 on 2023-10-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="items",
            new_name="course",
        ),
    ]
