# Generated by Django 4.2.6 on 2023-10-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_rename_items_transaction_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="course",
            new_name="items",
        ),
    ]
