# Generated by Django 4.2.6 on 2023-10-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_alter_course_pic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursesubtitle",
            old_name="sub_title",
            new_name="subtitle",
        ),
    ]
