# Generated by Django 4.2.6 on 2023-10-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_alter_course_pic_alter_coursevideo_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
