# Generated by Django 4.2.6 on 2023-10-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sessions", "0001_initial"),
        ("academy", "0008_card"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Card",
            new_name="Cart",
        ),
    ]
