# Generated by Django 4.2.6 on 2023-10-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_alter_transaction_customer"),
        (
            "academy",
            "0010_remove_order_transaction_order_customer_order_total_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total",
        ),
        migrations.AddField(
            model_name="order",
            name="transaction",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="checkout.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="ordercourse",
            name="price",
            field=models.FloatField(null=True),
        ),
    ]
