# Generated by Django 4.2.6 on 2023-10-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0011_remove_order_customer_remove_order_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordercourse",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
