# Generated by Django 4.2.6 on 2023-10-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0012_ordercourse_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursevideo",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
