# Generated by Django 4.2.6 on 2023-10-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0014_answer_comment_delete_membercourses_answer_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="approved",
        ),
    ]
