# Generated by Django 4.2.6 on 2023-10-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_alter_transaction_customer"),
        ("academy", "0016_alter_order_transaction_alter_ordercourse_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="checkout.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="ordercourse",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="academy.course",
            ),
        ),
        migrations.AlterField(
            model_name="ordercourse",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="academy.order",
            ),
        ),
    ]
